--liquibase formatted sql

--changeset changelog:1.1


-- create SEQ for TABLE department
CREATE SEQUENCE TEST.DEPARTMENT_SEQ
    INCREMENT BY 1
    START WITH 1001
;


-- CREATE TABLE DEPARTMENT

CREATE TABLE TEST.DEPARTMENT (
    ID NUMBER(12),
    NAME VARCHAR2(30),
    ACTIVE VARCHAR2(1) DEFAULT 'N',
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID)
);